# Generated by Django 4.2.7 on 2025-07-14 15:05

import django.core.validators
from django.db import migrations, models
import xray_search.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XRay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(help_text='Patient ID in format P00000 (e.g., P00128)', max_length=20, validators=[django.core.validators.RegexValidator('^P\\d{5}$', 'Patient ID must be in format P00000')])),
                ('image', models.ImageField(help_text='X-ray image file (PNG or JPEG)', upload_to=xray_search.models.xray_upload_path)),
                ('body_part', models.CharField(choices=[('Chest', 'Chest'), ('Knee', 'Knee'), ('Spine', 'Spine'), ('Hip', 'Hip'), ('Shoulder', 'Shoulder'), ('Ankle', 'Ankle'), ('Wrist', 'Wrist'), ('Elbow', 'Elbow'), ('Pelvis', 'Pelvis'), ('Abdomen', 'Abdomen')], help_text='Body part being X-rayed', max_length=50)),
                ('scan_date', models.DateField(help_text='Date when the X-ray scan was taken')),
                ('institution', models.CharField(help_text='Medical institution where scan was performed', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the X-ray findings')),
                ('diagnosis', models.CharField(help_text='Medical diagnosis based on the X-ray', max_length=200)),
                ('tags', models.JSONField(default=list, help_text="List of tags for categorization (e.g., ['lung', 'infection', 'opacity'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'X-ray Scan',
                'verbose_name_plural': 'X-ray Scans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['body_part'], name='xray_search_body_pa_3a957c_idx'), models.Index(fields=['diagnosis'], name='xray_search_diagnos_58797a_idx'), models.Index(fields=['institution'], name='xray_search_institu_5b62da_idx'), models.Index(fields=['scan_date'], name='xray_search_scan_da_240cef_idx'), models.Index(fields=['patient_id'], name='xray_search_patient_9a1c98_idx')],
            },
        ),
    ]
