# Generated by Django 4.2.7 on 2025-07-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xray',
            name='tags',
            field=models.JSONField(default=list, help_text='List of tags for categorization (e.g., ["lung", "infection", "opacity"])'),
        ),
    ]
