# Generated by Django 4.2.7 on 2025-07-15 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xray_search', '0002_alter_xray_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the body part (e.g., Chest, Knee)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this body part category includes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this body part is active for new X-rays')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Body Part Category',
                'verbose_name_plural': 'Body Part Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='xray',
            name='body_part',
            field=models.CharField(choices=[('Chest', 'Chest'), ('Knee', 'Knee'), ('Spine', 'Spine'), ('Hip', 'Hip'), ('Shoulder', 'Shoulder'), ('Ankle', 'Ankle'), ('Wrist', 'Wrist'), ('Elbow', 'Elbow'), ('Pelvis', 'Pelvis'), ('Abdomen', 'Abdomen')], help_text='Body part being X-rayed (for backward compatibility)', max_length=50),
        ),
        migrations.AddField(
            model_name='xray',
            name='body_part_category',
            field=models.ForeignKey(blank=True, help_text='Body part category (managed by admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='xray_search.bodypart'),
        ),
    ]
