# Generated by Django 4.2.7 on 2025-07-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xray_search', '0003_bodypart_alter_xray_body_part_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodypart',
            options={'ordering': ['name'], 'permissions': [('can_manage_body_parts', 'Can manage body part categories'), ('can_delete_body_parts', 'Can delete body part categories')], 'verbose_name': 'Body Part Category', 'verbose_name_plural': 'Body Part Categories'},
        ),
        migrations.AlterModelOptions(
            name='xray',
            options={'ordering': ['-created_at'], 'permissions': [('can_upload_xrays', 'Can upload X-ray scans'), ('can_delete_xrays', 'Can delete X-ray scans'), ('can_manage_xrays', 'Can manage X-ray scans')], 'verbose_name': 'X-ray Scan', 'verbose_name_plural': 'X-ray Scans'},
        ),
    ]
