# Generated by Django 4.2.7 on 2025-07-15 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray_search', '0004_alter_bodypart_options_alter_xray_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xray',
            name='patient_id',
            field=models.CharField(help_text='Patient ID in format P followed by numbers (e.g., P001211, P00128)', max_length=20, validators=[django.core.validators.RegexValidator('^P\\d+$', 'Patient ID must start with P followed by numbers')]),
        ),
    ]
