# Generated by Django 4.2.7 on 2025-07-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray_search', '0005_update_patient_id_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xray',
            name='body_part_category',
        ),
        migrations.AlterField(
            model_name='xray',
            name='body_part',
            field=models.CharField(help_text='Body part being X-rayed', max_length=50),
        ),
    ]
